### PR TITLE
Use a newly generated access_token while joining Jitsi

### LINKED ISSUE #24687: Authentication failure when joining Jitsi conference due to expired OIDC access token
### Steps to reproduce

1. click the video conference button or reactivate the conference widget in the Matrix room
2. wait for a while (_depending on the expire time set in your system, 1 hour by default_) without closing the Jitsi widget
3. click join conference button
4. the widget will open jitsi page but the conference will not be started because of the authentication failed error

This problem only occurs if `openidtoken-jwt` is enabled.

#### What did you expect?

The participant should join the video conference room since she is an active member of a Matrix room

#### What happened instead?

The participant cannot join the video conference and she gets `authentication failed` error.

### Operating system

Debian 11 Bullseye

### Browser information

Chromium Version 110.0.5481.177

### URL for webapp

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by emrahcom**
## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

This commit is related with `Jitsi` widget. It updates the token request time from the setup phase to the join phase. For now, `OIDC access token` is requested when initializing the widget. If the participant waits longer than the token expire time before clicking the `join conference` button, the participant gets the `authentication failed` error because of the expired OIDC token and they cannot join the video conference.

This problem only occurs if `openidtoken-jwt` is enabled.

The widget puts `OIDC access token` into `Jitsi token` as a field and it always uses the `access token` received at the widget setup time.

## Steps to reproduce the issue:
- click the video conference button or reactivate the conference widget in the Matrix room
- wait a while (_depending on the expire time set in your system_) without clicking join conference button which is inside the widget
- click join conference button
- the widget will open jitsi page but the conference will not be started because of the authentication failed error

## How does the issue occur:
- when jitsi widget is initialized in the Matrix room, it sends a request to Matrix server to get an access token
- A typical response is like the following
```json
{
"access_token":"KNYEtwBkaxKFwAxaOCapIjrE",
"token_type":"Bearer",
"matrix_server_name":"​ Element ",
"expires_in":3600
}
```
- the expire time for this access token is 3600 seconds. It is set by the server
- when the participant clicks join conference button, the widget puts this `access token` into JWT without renew it.
- if the participant has waited 3600 seconds before clicking the button then the authentication fails because of the expire time.

## How this commit solves the issue
It gets `OIDC access token` after clicking the `join conference` button, just before creating `JWT`.

Signed-off-by: Emrah Eryilmaz <emrah.com@gmail.com>
Fixes: https://github.com/vector-im/element-web/issues/24687

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Use a newly generated access_token while joining Jitsi ([\#24646](https://github.com/vector-im/element-web/pull/24646)). Fixes #24687. Contributed by @emrahcom.

### CODE REVIEW

File: src/vector/jitsi/index.ts [hunk 1]
```diff
@@ -345,9 +338,13 @@ function mapLanguage(language: string): string {
 // audio input it can find, while an input of null instructs it to start muted,
 // and a non-nullish input specifies the label of a specific device to use.
 // Same for video inputs.
-function joinConference(audioInput?: string | null, videoInput?: string | null): void {
+async function joinConference(audioInput?: string | null, videoInput?: string | null): Promise<void> {
     let jwt;
     if (jitsiAuth === JITSI_OPENIDTOKEN_JWT_AUTH) {
+        // Request credentials, give callback to continue when received
```
Comment (richvdh) [inline src/vector/jitsi/index.ts:344]: I don't understand this comment. If it also makes no sense to you, I suggest we remove it rather than copying it.

**Review by richvdh — COMMENTED** [review]
Hi @emrahcom thank you for your contribution! A couple of requests:

1. Please could you open a new issue clearly describing the problem you are fixing. I know that you have described it in the PR description, but it is somewhat confusing to have it mixed in with an explanation of the fix.

2. It looks like we will now request a new `openIdToken` every time we try to join the call. It seems like that will involve a number of HTTP requests at least. Can we cache the results of a successful authentication?

File: src/vector/jitsi/index.ts [hunk 2]
```diff
@@ -212,13 +212,6 @@ const setupCompleted = (async (): Promise<string | void> => {
 
         if (widgetApi) {
             await widgetApiReady;
-
-            // See https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification
```
Comment (turt2live) [inline src/vector/jitsi/index.ts:216]: ideally we'd keep this comment though

**Comment by richvdh** [comment]
> It looks like we will now request a new openIdToken every time we try to join the call. It seems like that will involve a number of HTTP requests at least. Can we cache the results of a successful authentication?

@turt2live tells me that the lifetime of the openId tokens is relatively short, so caching them is not worthwhile. Please ignore this suggestion!

File: src/vector/jitsi/index.ts [hunk 3]
```diff
@@ -345,9 +338,13 @@ function mapLanguage(language: string): string {
 // audio input it can find, while an input of null instructs it to start muted,
 // and a non-nullish input specifies the label of a specific device to use.
 // Same for video inputs.
-function joinConference(audioInput?: string | null, videoInput?: string | null): void {
+async function joinConference(audioInput?: string | null, videoInput?: string | null): Promise<void> {
     let jwt;
     if (jitsiAuth === JITSI_OPENIDTOKEN_JWT_AUTH) {
+        // Request credentials, give callback to continue when received
+        openIdToken = await widgetApi.requestOpenIDConnectToken();
```
Comment (richvdh) [inline src/vector/jitsi/index.ts:345]: now that `openIdToken` is only used here (and in `createJWTToken`, where we can just pass it in): could we make it a local, rather than a global, variable?

**Comment by emrahcom** [comment]
>     1. Please could you open a new issue clearly describing the (symptoms of the) problem you are fixing. I know that you have described it in the PR description, but it is somewhat confusing to have it mixed in with an explanation of the fix.

Issue #24687

**Comment by andybalaam** [comment]
@emrahcom what is the state of this PR? Are you waiting for feedback? It looks to me from the comments like we're waiting for you to respond to the reviewer feedback. Is that right? If so, I recommend moving its status back to Draft until it's ready.

Thanks for the contribution!

**Comment by emrahcom** [comment]
> @emrahcom what is the state of this PR? Are you waiting for feedback? It looks to me from the comments like we're waiting for you to respond to the reviewer feedback. Is that right?

No, I'm waiting for you. I think the PR is already ready.

**Comment by andybalaam** [comment]
> No, I'm waiting for you. I think the PR is already ready. The updates according to the reviewer feedback were applied 3 weeks ago

OK, I clicked "Re-request review" so @richvdh knows you're looking for more feedback.

**Comment by richvdh** [comment]
> > @emrahcom did this happen:
> 
> Yep, Issue #24687

Thanks, have linked it from the PR description

File: src/vector/jitsi/index.ts [hunk 4]
```diff
@@ -356,17 +348,21 @@ function mapLanguage(language: string): string {
...
 // Same for video inputs.
-function joinConference(audioInput?: string | null, videoInput?: string | null): void {
+async function joinConference(audioInput?: string | null, videoInput?: string | null): Promise<void> {
     let jwt;
     if (jitsiAuth === JITSI_OPENIDTOKEN_JWT_AUTH) {
+        // See https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification
+        const openIdToken: IOpenIDCredentials = await widgetApi.requestOpenIDConnectToken();
+        logger.log("Got OpenID Connect token");
+
         if (!openIdToken?.access_token) {
```
Comment (richvdh) [inline src/vector/jitsi/index.ts:358]: `openIdToken` now cannot be `null` or `undefined`, so the `?` is redundant

```suggestion
        if (!openIdToken.access_token) {
```

**Review by richvdh — APPROVED** [review]
Thanks for this! Looks good!
