### PR TITLE
Ensure group audio-only calls don't switch on the webcam on join

### LINKED ISSUE #20212: Calling turns on video without participant consent.
### Steps to reproduce

1. In a group chat, start or join a jitsi call (even when clicking the "voice call" button).
2. Your camera is now on, without consent or warning, and visible to anyone connecting to your call.

#### What did you expect?
I expected that there would at least be a warning if it were to turn on, and if anything, hitting "voice call" wouldn't have turned on my camera.
#### What happened instead?
My camera was immediately turned on.

### Operating system

_No response_

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### How did you install the app?

https://community.chocolatey.org/packages/element-desktop

### Homeserver

yiff.social

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by novocaine**
Fixes https://github.com/vector-im/element-web/issues/20212

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Ensure group audio-only calls don't switch on the webcam on join ([\#20234](https://github.com/vector-im/element-web/pull/20234)). Fixes #20212. Contributed by @novocaine.

### CODE REVIEW

File: src/vector/jitsi/index.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ let jitsiAuth: string;
 let roomId: string;
 let openIdToken: IOpenIDCredentials;
 let roomName: string;
+let startAudioOnly: string;
```
Comment (turt2live) [inline src/vector/jitsi/index.ts:49]: boolean? Worried that `"false"` gets treated as true.

Comment (novocaine) [reply src/vector/jitsi/index.ts]: 🤦 thanks

**Review by turt2live — APPROVED** [review]

**Review by SimonBrandner — APPROVED** [review]
Could you please add some note for the end-user to see in the changelog? The current title isn't very user friendly. Otherwise, LGTM, thanks!
